### ISSUE TITLE
Netgear official repo?

### ISSUE THREAD

**Issue by marcosfrm** [Netgear/wsdd2#24]
https://github.com/Netgear/wsdd2

It is official Netgear account... are they willing to proper maintain the code?

**Comment by Andy2244** [comment]
> It is official Netgear account... are they willing to proper maintain the code?

Not sure, maybe just forked it as source for there next ReadyNAS OS version, since there org. version was not updated since 2019 and i doubt that the original authors are cycling back to this.

PS: I still want to play around with the maintained [python version](https://github.com/christgau/wsdd) and build it as static bin. Yet after i merged some actual updates/fixes to our wsdd2 package a lot of code issues are fixed now, so it became a lower priority.

**Comment by paul-chambers** [comment]
Funnily enough, we've been using the enterprise version of github internally for some time, but haven't had an official public presence on github.com. Now we do :)

We'd be willing to move the wsdd2 repo over, if Andy2244 is willing. Though I suggest Andy2244 stays on as a maintainer if so. I'm relatively new to Netgear myself, and don't know the history of the `wsdd2` project. I also don't know if the original author(s) are still at Netgear, so don't know if we're in a better position to support the existing code than the community is. Particularly since I work on the router firmware, not the NAS products.

**Comment by Andy2244** [comment]
I'm fine either way, we only added a few parameter at first and fixed some minor bugs. Early this year [Volodymyr Prodan](https://github.com/vovcat/wsdd2) did some actual rework and fixing again and i merged those changes. Yet so far no new changes, so my guess is we are in maintenance mode again. Not a big deal, since most seems to work ok now.

**Comment by paul-chambers** [comment]
Hi Andy - just sent you an invite to the Netgear org on github. Once you accept it, could you please transfer the wsdd2 repo over to the Netgear organization?  I would still like you to 'shepherd' it, if you're willing. Continuity is good :)

**Comment by Andy2244** [comment]
@paul-chambers sure done

**Comment by marcosfrm** [comment]
Great!

**Comment by paul-chambers** [comment]
Thanks, Andy.

You're now an 'outside contributor' to the Netgear org, with 'maintain' rights on that repo. That should be equivalent to the rights you had.

I also created and added you to a new team I called 'Community'. Not used for anything yet, but seems like something we might need at some point.
